<a href="https://colab.research.google.com/github/ChrisO27/machinelearning-az/blob/master/SECTION%202%3A%20SIMPLE%20LINEAR%20REGRESSION/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [23]:
dataset = pd.read_csv('https://raw.githubusercontent.com/joanby/machinelearning-az/master/update/Part%202%20-%20Regression/Section%205%20-%20Multiple%20Linear%20Regression/Python/50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [24]:
print(X[:5,:])

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']]


## Encoding categorical data

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [26]:
# Quitar la primera variable
X = X[:,1:]

In [27]:
print(X[:5,:])

[[0.0 1.0 165349.2 136897.8 471784.1]
 [0.0 0.0 162597.7 151377.59 443898.53]
 [1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 1.0 144372.41 118671.85 383199.62]
 [1.0 0.0 142107.34 91391.77 366168.42]]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [35]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [38]:
# Suponiendo que tu modelo se llama 'modelo'
coeficientes = regressor.coef_  # Obtiene los coeficientes (pendiente)
intercepto = regressor.intercept_  # Obtiene el término independiente

print("Coeficientes:", [f"{coef:.2f}" for coef in coeficientes])
print("Intercepto:", intercepto)

Coeficientes: ['-959.28', '699.37', '0.77', '0.03', '0.04']
Intercepto: 42554.167617767


## Predicting the Test set results

In [40]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
#######
y_pred = y_pred.reshape(len(y_pred),1)
y_test = y_test.reshape(len(y_test),1)
print(np.concatenate((y_pred, y_test,y_pred - y_test),1))

[[103015.2  103282.38   -267.18]
 [132582.28 144259.4  -11677.12]
 [132447.74 146121.95 -13674.21]
 [ 71976.1   77798.83  -5822.73]
 [178537.48 191050.39 -12512.91]
 [116161.24 105008.31  11152.93]
 [ 67851.69  81229.06 -13377.37]
 [ 98791.73  97483.56   1308.17]
 [113969.44 110352.25   3617.19]
 [167921.07 166187.94   1733.13]]
